version: "3.8"

services:
  agent_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    ports:
      - "8000:8000"
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/info"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  streamlit_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - agent_service
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    environment:
      - AGENT_URL=http://agent_service:8000
