version: "3.8"

services:
  agent_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    ports:
      - "8000:8000"
    env_file:
      - .env

  streamlit_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - agent_service
    env_file:
      - .env
    environment:
      - AGENT_URL=http://agent_service:8000
