services:
  agent_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CHINOOK_DB_PATH=/app/data/Chinook.db
      - SQLITE_DB_PATH=/app/checkpoints.db
    volumes:
      - data_volume:/app/data
      - chroma_volume:/app/chroma_db
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  streamlit_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      agent_service:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - AGENT_URL=http://agent_service:8000
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

volumes:
  data_volume:
  chroma_volume:
